"""Report rendering helpers for the validation suite."""

from pathlib import Path


def summarize(results):
    required = [item for item in results if item["required"]]
    optional = [item for item in results if not item["required"]]
    failed_required = [item for item in required if item["status"] != "pass"]
    failed_optional = [item for item in optional if item["status"] != "pass"]
    return {
        "total_checks": len(results),
        "required_checks": len(required),
        "optional_checks": len(optional),
        "failed_required": len(failed_required),
        "failed_optional": len(failed_optional),
        "status": "pass" if not failed_required else "fail",
    }


def write_markdown(path, report):
    lines = [
        "<!-- GENERATED by tools/validation_suite.py; use --output-md to write scratch reports elsewhere. -->",
        "",
        "# Validation Suite Report",
        "",
        f"- status: {report['summary']['status']}",
        f"- mode: {report['mode']}",
        f"- total_checks: {report['summary']['total_checks']}",
        f"- failed_required: {report['summary']['failed_required']}",
        f"- failed_optional: {report['summary']['failed_optional']}",
        "",
        "| Check | Required | Status | Seconds |",
        "| --- | --- | --- | ---: |",
    ]
    for item in report["checks"]:
        lines.append(
            "| `{}` | {} | {} | {:.3f} |".format(
                item["name"],
                str(item["required"]).lower(),
                item["status"],
                item["duration_seconds"],
            )
        )
    lines.extend(["", "## Failed Checks"])
    failed = [item for item in report["checks"] if item["status"] != "pass"]
    if not failed:
        lines.append("- none")
    for item in failed:
        lines.append(f"### {item['name']}")
        lines.append(f"- required: {str(item['required']).lower()}")
        lines.append(f"- command: `{' '.join(item['command'])}`")
        lines.append(f"- returncode: `{item['returncode']}`")
        if item["stderr_tail"]:
            lines.append("")
            lines.append("```text")
            lines.append(item["stderr_tail"].rstrip())
            lines.append("```")
        if item["stdout_tail"]:
            lines.append("")
            lines.append("```text")
            lines.append(item["stdout_tail"].rstrip())
            lines.append("```")
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
